services:
  - type: web
    name: three-of-spades-frontend
    env: static
    plan: free
    region: oregon
    buildCommand: npm install && npm run build
    staticPublishPath: dist
    envVars:
      - key: VITE_API_BASE_URL
        value: https://three-of-spades-backend.onrender.com/api
      - key: VITE_WS_URL
        value: wss://three-of-spades-backend.onrender.com/ws

services:
  - type: web
    name: three-of-spades-backend
    env: java
    plan: free
    region: oregon
    buildCommand: ./mvnw -DskipTests package
    startCommand: java -jar target/backend-0.0.1-SNAPSHOT.jar
    envVars:
      - key: PORT
        value: 10000

